// Vocabulary data.
// Furigana syntax: kanji[reading] — reading applies to the contiguous kanji
// immediately before the bracket. For mixed kanji+kana words, bracket each
// kanji group separately, e.g. "食[た]べ物[もの]".

const VOCAB = [
  { jp: "私[わたし]", en: "I, me", level: "N5" },
  { jp: "私達[わたしたち]", en: "we", level: "N5" },
  { jp: "貴方[あなた]", en: "you", level: "N5" },
  { jp: "彼[かれ]", en: "he, boyfriend", level: "N5" },
  { jp: "彼女[かのじょ]", en: "she, girlfriend", level: "N5" },
  { jp: "人[ひと]", en: "person", level: "N5" },
  { jp: "方[かた]", en: "person (polite)", level: "N5" },
  { jp: "男[おとこ]", en: "man", level: "N5" },
  { jp: "女[おんな]", en: "woman", level: "N5" },
  { jp: "男[おとこ]の人[ひと]", en: "man", level: "N5" },
  { jp: "女[おんな]の人[ひと]", en: "woman", level: "N5" },
  { jp: "男[おとこ]の子[こ]", en: "boy", level: "N5" },
  { jp: "女[おんな]の子[こ]", en: "girl", level: "N5" },
  { jp: "子供[こども]", en: "child", level: "N5" },
  { jp: "大人[おとな]", en: "adult", level: "N5" },
  { jp: "外国人[がいこくじん]", en: "foreigner", level: "N5" },
  { jp: "家族[かぞく]", en: "family", level: "N5" },
  { jp: "ご家族[かぞく]", en: "family (someone else's)", level: "N5" },
  { jp: "両親[りょうしん]", en: "parents", level: "N5" },
  { jp: "父[ちち]", en: "father (own)", level: "N5" },
  { jp: "母[はは]", en: "mother (own)", level: "N5" },
  { jp: "お父[とう]さん", en: "father", level: "N5" },
  { jp: "お母[かあ]さん", en: "mother", level: "N5" },
  { jp: "兄[あに]", en: "older brother (own)", level: "N5" },
  { jp: "姉[あね]", en: "older sister (own)", level: "N5" },
  { jp: "お兄[にい]さん", en: "older brother", level: "N5" },
  { jp: "お姉[ねえ]さん", en: "older sister", level: "N5" },
  { jp: "弟[おとうと]", en: "younger brother", level: "N5" },
  { jp: "妹[いもうと]", en: "younger sister", level: "N5" },
  { jp: "兄弟[きょうだい]", en: "siblings", level: "N5" },
  { jp: "夫[おっと]", en: "husband (own)", level: "N5" },
  { jp: "主人[しゅじん]", en: "husband", level: "N5" },
  { jp: "ご主人[しゅじん]", en: "husband (someone else's)", level: "N5" },
  { jp: "妻[つま]", en: "wife (own)", level: "N5" },
  { jp: "家内[かない]", en: "wife (own)", level: "N5" },
  { jp: "奥[おく]さん", en: "wife (someone else's)", level: "N5" },
  { jp: "おじさん", en: "uncle, middle-aged man", level: "N5" },
  { jp: "おばさん", en: "aunt, middle-aged woman", level: "N5" },
  { jp: "おじいさん", en: "grandfather, old man", level: "N5" },
  { jp: "おばあさん", en: "grandmother, old woman", level: "N5" },
  { jp: "友達[ともだち]", en: "friend", level: "N5" },
  { jp: "先生[せんせい]", en: "teacher", level: "N5" },
  { jp: "学生[がくせい]", en: "student", level: "N5" },
  { jp: "留学生[りゅうがくせい]", en: "exchange student", level: "N5" },
  { jp: "医者[いしゃ]", en: "doctor", level: "N5" },
  { jp: "警察[けいさつ]", en: "police", level: "N5" },
  { jp: "お巡[まわ]りさん", en: "police officer", level: "N5" },
  { jp: "会社員[かいしゃいん]", en: "company employee", level: "N5" },
  { jp: "店員[てんいん]", en: "shop clerk", level: "N5" },
  { jp: "皆[みんな]", en: "everyone", level: "N5" },
  { jp: "皆[みな]さん", en: "everyone (polite)", level: "N5" },
  { jp: "自分[じぶん]", en: "oneself", level: "N5" },
  { jp: "名前[なまえ]", en: "name", level: "N5" },
  { jp: "体[からだ]", en: "body", level: "N5" },
  { jp: "頭[あたま]", en: "head", level: "N5" },
  { jp: "顔[かお]", en: "face", level: "N5" },
  { jp: "目[め]", en: "eye", level: "N5" },
  { jp: "耳[みみ]", en: "ear", level: "N5" },
  { jp: "鼻[はな]", en: "nose", level: "N5" },
  { jp: "口[くち]", en: "mouth", level: "N5" },
  { jp: "歯[は]", en: "tooth", level: "N5" },
  { jp: "首[くび]", en: "neck", level: "N5" },
  { jp: "手[て]", en: "hand", level: "N5" },
  { jp: "足[あし]", en: "leg, foot", level: "N5" },
  { jp: "お腹[なか]", en: "stomach, belly", level: "N5" },
  { jp: "背[せ]", en: "back, height", level: "N5" },
  { jp: "髪[かみ]", en: "hair", level: "N5" },
  { jp: "声[こえ]", en: "voice", level: "N5" },
  { jp: "病気[びょうき]", en: "illness", level: "N5" },
  { jp: "風邪[かぜ]", en: "cold (illness)", level: "N5" },
  { jp: "熱[ねつ]", en: "fever, heat", level: "N5" },
  { jp: "薬[くすり]", en: "medicine", level: "N5" },
  { jp: "元気[げんき]", en: "energetic, well", level: "N5" },
  { jp: "食[た]べ物[もの]", en: "food", level: "N5" },
  { jp: "飲[の]み物[もの]", en: "drink", level: "N5" },
  { jp: "朝[あさ]ご飯[はん]", en: "breakfast", level: "N5" },
  { jp: "昼[ひる]ご飯[はん]", en: "lunch", level: "N5" },
  { jp: "晩[ばん]ご飯[はん]", en: "dinner", level: "N5" },
  { jp: "夕飯[ゆうはん]", en: "dinner", level: "N5" },
  { jp: "ご飯[はん]", en: "rice, meal", level: "N5" },
  { jp: "お弁当[べんとう]", en: "boxed lunch", level: "N5" },
  { jp: "パン", en: "bread", level: "N5" },
  { jp: "肉[にく]", en: "meat", level: "N5" },
  { jp: "牛肉[ぎゅうにく]", en: "beef", level: "N5" },
  { jp: "豚肉[ぶたにく]", en: "pork", level: "N5" },
  { jp: "鶏肉[とりにく]", en: "chicken (meat)", level: "N5" },
  { jp: "魚[さかな]", en: "fish", level: "N5" },
  { jp: "野菜[やさい]", en: "vegetable", level: "N5" },
  { jp: "果物[くだもの]", en: "fruit", level: "N5" },
  { jp: "りんご", en: "apple", level: "N5" },
  { jp: "みかん", en: "mandarin orange", level: "N5" },
  { jp: "バナナ", en: "banana", level: "N5" },
  { jp: "卵[たまご]", en: "egg", level: "N5" },
  { jp: "牛乳[ぎゅうにゅう]", en: "milk", level: "N5" },
  { jp: "バター", en: "butter", level: "N5" },
  { jp: "チーズ", en: "cheese", level: "N5" },
  { jp: "塩[しお]", en: "salt", level: "N5" },
  { jp: "砂糖[さとう]", en: "sugar", level: "N5" },
  { jp: "醤油[しょうゆ]", en: "soy sauce", level: "N5" },
  { jp: "味噌[みそ]", en: "miso", level: "N5" },
  { jp: "お菓子[かし]", en: "sweets, snacks", level: "N5" },
  { jp: "お酒[さけ]", en: "alcohol, sake", level: "N5" },
  { jp: "ビール", en: "beer", level: "N5" },
  { jp: "ワイン", en: "wine", level: "N5" },
  { jp: "水[みず]", en: "water", level: "N5" },
  { jp: "お湯[ゆ]", en: "hot water", level: "N5" },
  { jp: "お茶[ちゃ]", en: "tea", level: "N5" },
  { jp: "紅茶[こうちゃ]", en: "black tea", level: "N5" },
  { jp: "コーヒー", en: "coffee", level: "N5" },
  { jp: "ジュース", en: "juice", level: "N5" },
  { jp: "カレー", en: "curry", level: "N5" },
  { jp: "ラーメン", en: "ramen", level: "N5" },
  { jp: "寿司[すし]", en: "sushi", level: "N5" },
  { jp: "天[てん]ぷら", en: "tempura", level: "N5" },
  { jp: "レストラン", en: "restaurant", level: "N5" },
  { jp: "喫茶店[きっさてん]", en: "coffee shop", level: "N5" },
  { jp: "食堂[しょくどう]", en: "dining hall", level: "N5" },
  { jp: "茶碗[ちゃわん]", en: "rice bowl", level: "N5" },
  { jp: "コップ", en: "cup, glass", level: "N5" },
  { jp: "皿[さら]", en: "plate", level: "N5" },
  { jp: "箸[はし]", en: "chopsticks", level: "N5" },
  { jp: "フォーク", en: "fork", level: "N5" },
  { jp: "スプーン", en: "spoon", level: "N5" },
  { jp: "ナイフ", en: "knife", level: "N5" },
  { jp: "動物[どうぶつ]", en: "animal", level: "N5" },
  { jp: "犬[いぬ]", en: "dog", level: "N5" },
  { jp: "猫[ねこ]", en: "cat", level: "N5" },
  { jp: "鳥[とり]", en: "bird", level: "N5" },
  { jp: "馬[うま]", en: "horse", level: "N5" },
  { jp: "牛[うし]", en: "cow", level: "N5" },
  { jp: "豚[ぶた]", en: "pig", level: "N5" },
  { jp: "木[き]", en: "tree, wood", level: "N5" },
  { jp: "花[はな]", en: "flower", level: "N5" },
  { jp: "山[やま]", en: "mountain", level: "N5" },
  { jp: "川[かわ]", en: "river", level: "N5" },
  { jp: "海[うみ]", en: "sea, ocean", level: "N5" },
  { jp: "湖[みずうみ]", en: "lake", level: "N5" },
  { jp: "池[いけ]", en: "pond", level: "N5" },
  { jp: "空[そら]", en: "sky", level: "N5" },
  { jp: "雲[くも]", en: "cloud", level: "N5" },
  { jp: "月[つき]", en: "moon", level: "N5" },
  { jp: "星[ほし]", en: "star", level: "N5" },
  { jp: "太陽[たいよう]", en: "sun", level: "N5" },
  { jp: "天気[てんき]", en: "weather", level: "N5" },
  { jp: "雨[あめ]", en: "rain", level: "N5" },
  { jp: "雪[ゆき]", en: "snow", level: "N5" },
  { jp: "風[かぜ]", en: "wind", level: "N5" },
  { jp: "火[ひ]", en: "fire", level: "N5" },
  { jp: "石[いし]", en: "stone", level: "N5" },
  { jp: "土[つち]", en: "soil, earth", level: "N5" },
  { jp: "森[もり]", en: "forest", level: "N5" },
  { jp: "公園[こうえん]", en: "park", level: "N5" },
  { jp: "庭[にわ]", en: "garden", level: "N5" },
  { jp: "時間[じかん]", en: "time, hour", level: "N5" },
  { jp: "今[いま]", en: "now", level: "N5" },
  { jp: "今日[きょう]", en: "today", level: "N5" },
  { jp: "明日[あした]", en: "tomorrow", level: "N5" },
  { jp: "昨日[きのう]", en: "yesterday", level: "N5" },
  { jp: "明後日[あさって]", en: "day after tomorrow", level: "N5" },
  { jp: "一昨日[おととい]", en: "day before yesterday", level: "N5" },
  { jp: "毎日[まいにち]", en: "every day", level: "N5" },
  { jp: "毎朝[まいあさ]", en: "every morning", level: "N5" },
  { jp: "毎晩[まいばん]", en: "every night", level: "N5" },
  { jp: "毎週[まいしゅう]", en: "every week", level: "N5" },
  { jp: "毎月[まいつき]", en: "every month", level: "N5" },
  { jp: "毎年[まいとし]", en: "every year", level: "N5" },
  { jp: "朝[あさ]", en: "morning", level: "N5" },
  { jp: "昼[ひる]", en: "noon, daytime", level: "N5" },
  { jp: "夕方[ゆうがた]", en: "evening", level: "N5" },
  { jp: "晩[ばん]", en: "evening, night", level: "N5" },
  { jp: "夜[よる]", en: "night", level: "N5" },
  { jp: "午前[ごぜん]", en: "AM, morning", level: "N5" },
  { jp: "午後[ごご]", en: "PM, afternoon", level: "N5" },
  { jp: "今朝[けさ]", en: "this morning", level: "N5" },
  { jp: "今晩[こんばん]", en: "tonight", level: "N5" },
  { jp: "今週[こんしゅう]", en: "this week", level: "N5" },
  { jp: "来週[らいしゅう]", en: "next week", level: "N5" },
  { jp: "先週[せんしゅう]", en: "last week", level: "N5" },
  { jp: "今月[こんげつ]", en: "this month", level: "N5" },
  { jp: "来月[らいげつ]", en: "next month", level: "N5" },
  { jp: "先月[せんげつ]", en: "last month", level: "N5" },
  { jp: "今年[ことし]", en: "this year", level: "N5" },
  { jp: "来年[らいねん]", en: "next year", level: "N5" },
  { jp: "去年[きょねん]", en: "last year", level: "N5" },
  { jp: "週[しゅう]", en: "week", level: "N5" },
  { jp: "週間[しゅうかん]", en: "week (counter)", level: "N5" },
  { jp: "年[とし]", en: "year, age", level: "N5" },
  { jp: "曜日[ようび]", en: "day of the week", level: "N5" },
  { jp: "日曜日[にちようび]", en: "Sunday", level: "N5" },
  { jp: "月曜日[げつようび]", en: "Monday", level: "N5" },
  { jp: "火曜日[かようび]", en: "Tuesday", level: "N5" },
  { jp: "水曜日[すいようび]", en: "Wednesday", level: "N5" },
  { jp: "木曜日[もくようび]", en: "Thursday", level: "N5" },
  { jp: "金曜日[きんようび]", en: "Friday", level: "N5" },
  { jp: "土曜日[どようび]", en: "Saturday", level: "N5" },
  { jp: "誕生日[たんじょうび]", en: "birthday", level: "N5" },
  { jp: "休[やす]み", en: "rest, holiday, vacation", level: "N5" },
  { jp: "夏休[なつやす]み", en: "summer vacation", level: "N5" },
  { jp: "春[はる]", en: "spring", level: "N5" },
  { jp: "夏[なつ]", en: "summer", level: "N5" },
  { jp: "秋[あき]", en: "autumn", level: "N5" },
  { jp: "冬[ふゆ]", en: "winter", level: "N5" },
  { jp: "一月[いちがつ]", en: "January", level: "N5" },
  { jp: "二月[にがつ]", en: "February", level: "N5" },
  { jp: "三月[さんがつ]", en: "March", level: "N5" },
  { jp: "四月[しがつ]", en: "April", level: "N5" },
  { jp: "五月[ごがつ]", en: "May", level: "N5" },
  { jp: "六月[ろくがつ]", en: "June", level: "N5" },
  { jp: "七月[しちがつ]", en: "July", level: "N5" },
  { jp: "八月[はちがつ]", en: "August", level: "N5" },
  { jp: "九月[くがつ]", en: "September", level: "N5" },
  { jp: "十月[じゅうがつ]", en: "October", level: "N5" },
  { jp: "十一月[じゅういちがつ]", en: "November", level: "N5" },
  { jp: "十二月[じゅうにがつ]", en: "December", level: "N5" },
  { jp: "零[ゼロ]", en: "zero", level: "N5" },
  { jp: "一[いち]", en: "one", level: "N5" },
  { jp: "二[に]", en: "two", level: "N5" },
  { jp: "三[さん]", en: "three", level: "N5" },
  { jp: "四[よん]", en: "four", level: "N5" },
  { jp: "五[ご]", en: "five", level: "N5" },
  { jp: "六[ろく]", en: "six", level: "N5" },
  { jp: "七[なな]", en: "seven", level: "N5" },
  { jp: "八[はち]", en: "eight", level: "N5" },
  { jp: "九[きゅう]", en: "nine", level: "N5" },
  { jp: "十[じゅう]", en: "ten", level: "N5" },
  { jp: "百[ひゃく]", en: "hundred", level: "N5" },
  { jp: "千[せん]", en: "thousand", level: "N5" },
  { jp: "万[まん]", en: "ten thousand", level: "N5" },
  { jp: "円[えん]", en: "yen", level: "N5" },
  { jp: "個[こ]", en: "counter for small objects", level: "N5" },
  { jp: "枚[まい]", en: "counter for flat objects", level: "N5" },
  { jp: "本[ほん]", en: "counter for long objects", level: "N5" },
  { jp: "匹[ひき]", en: "counter for small animals", level: "N5" },
  { jp: "回[かい]", en: "times (counter)", level: "N5" },
  { jp: "階[かい]", en: "floor (counter)", level: "N5" },
  { jp: "番[ばん]", en: "number (in a series)", level: "N5" },
  { jp: "歳[さい]", en: "years old", level: "N5" },
  { jp: "半分[はんぶん]", en: "half", level: "N5" },
  { jp: "半[はん]", en: "half", level: "N5" },
  { jp: "幾[いく]つ", en: "how many, how old", level: "N5" },
  { jp: "幾[いく]ら", en: "how much", level: "N5" },
  { jp: "沢山[たくさん]", en: "many, a lot", level: "N5" },
  { jp: "少[すこ]し", en: "a little", level: "N5" },
  { jp: "全部[ぜんぶ]", en: "all, entire", level: "N5" },
  { jp: "所[ところ]", en: "place", level: "N5" },
  { jp: "家[いえ]", en: "house, home", level: "N5" },
  { jp: "うち", en: "home, one's own", level: "N5" },
  { jp: "部屋[へや]", en: "room", level: "N5" },
  { jp: "台所[だいどころ]", en: "kitchen", level: "N5" },
  { jp: "風呂[ふろ]", en: "bath", level: "N5" },
  { jp: "お風呂[ふろ]", en: "bath", level: "N5" },
  { jp: "トイレ", en: "toilet", level: "N5" },
  { jp: "お手洗[てあら]い", en: "restroom", level: "N5" },
  { jp: "玄関[げんかん]", en: "entrance", level: "N5" },
  { jp: "学校[がっこう]", en: "school", level: "N5" },
  { jp: "大学[だいがく]", en: "university", level: "N5" },
  { jp: "高校[こうこう]", en: "high school", level: "N5" },
  { jp: "中学校[ちゅうがっこう]", en: "junior high school", level: "N5" },
  { jp: "小学校[しょうがっこう]", en: "elementary school", level: "N5" },
  { jp: "教室[きょうしつ]", en: "classroom", level: "N5" },
  { jp: "図書館[としょかん]", en: "library", level: "N5" },
  { jp: "病院[びょういん]", en: "hospital", level: "N5" },
  { jp: "銀行[ぎんこう]", en: "bank", level: "N5" },
  { jp: "郵便局[ゆうびんきょく]", en: "post office", level: "N5" },
  { jp: "会社[かいしゃ]", en: "company", level: "N5" },
  { jp: "事務所[じむしょ]", en: "office", level: "N5" },
  { jp: "店[みせ]", en: "shop, store", level: "N5" },
  { jp: "本屋[ほんや]", en: "bookstore", level: "N5" },
  { jp: "八百屋[やおや]", en: "vegetable shop", level: "N5" },
  { jp: "肉屋[にくや]", en: "butcher", level: "N5" },
  { jp: "魚屋[さかなや]", en: "fish shop", level: "N5" },
  { jp: "デパート", en: "department store", level: "N5" },
  { jp: "スーパー", en: "supermarket", level: "N5" },
  { jp: "コンビニ", en: "convenience store", level: "N5" },
  { jp: "市場[いちば]", en: "market", level: "N5" },
  { jp: "ホテル", en: "hotel", level: "N5" },
  { jp: "映画館[えいがかん]", en: "movie theater", level: "N5" },
  { jp: "美術館[びじゅつかん]", en: "art museum", level: "N5" },
  { jp: "建物[たてもの]", en: "building", level: "N5" },
  { jp: "ビル", en: "building (Western-style)", level: "N5" },
  { jp: "町[まち]", en: "town", level: "N5" },
  { jp: "市[し]", en: "city", level: "N5" },
  { jp: "国[くに]", en: "country", level: "N5" },
  { jp: "外国[がいこく]", en: "foreign country", level: "N5" },
  { jp: "東京[とうきょう]", en: "Tokyo", level: "N5" },
  { jp: "日本[にほん]", en: "Japan", level: "N5" },
  { jp: "道[みち]", en: "road, way", level: "N5" },
  { jp: "橋[はし]", en: "bridge", level: "N5" },
  { jp: "角[かど]", en: "corner", level: "N5" },
  { jp: "交差点[こうさてん]", en: "intersection", level: "N5" },
  { jp: "信号[しんごう]", en: "traffic light, signal", level: "N5" },
  { jp: "地図[ちず]", en: "map", level: "N5" },
  { jp: "住所[じゅうしょ]", en: "address", level: "N5" },
  { jp: "近所[きんじょ]", en: "neighborhood", level: "N5" },
  { jp: "隣[となり]", en: "next door, neighbor", level: "N5" },
  { jp: "車[くるま]", en: "car", level: "N5" },
  { jp: "自動車[じどうしゃ]", en: "automobile", level: "N5" },
  { jp: "自転車[じてんしゃ]", en: "bicycle", level: "N5" },
  { jp: "バイク", en: "motorcycle", level: "N5" },
  { jp: "バス", en: "bus", level: "N5" },
  { jp: "タクシー", en: "taxi", level: "N5" },
  { jp: "電車[でんしゃ]", en: "train", level: "N5" },
  { jp: "地下鉄[ちかてつ]", en: "subway", level: "N5" },
  { jp: "新幹線[しんかんせん]", en: "bullet train", level: "N5" },
  { jp: "飛行機[ひこうき]", en: "airplane", level: "N5" },
  { jp: "船[ふね]", en: "ship, boat", level: "N5" },
  { jp: "駅[えき]", en: "station", level: "N5" },
  { jp: "空港[くうこう]", en: "airport", level: "N5" },
  { jp: "切符[きっぷ]", en: "ticket", level: "N5" },
  { jp: "切符売[きっぷう]り場[ば]", en: "ticket counter", level: "N5" },
  { jp: "物[もの]", en: "thing", level: "N5" },
  { jp: "事[こと]", en: "thing (abstract)", level: "N5" },
  { jp: "机[つくえ]", en: "desk", level: "N5" },
  { jp: "椅子[いす]", en: "chair", level: "N5" },
  { jp: "ベッド", en: "bed", level: "N5" },
  { jp: "テーブル", en: "table", level: "N5" },
  { jp: "戸[と]", en: "door", level: "N5" },
  { jp: "ドア", en: "door", level: "N5" },
  { jp: "窓[まど]", en: "window", level: "N5" },
  { jp: "鍵[かぎ]", en: "key, lock", level: "N5" },
  { jp: "電気[でんき]", en: "electricity, light", level: "N5" },
  { jp: "電話[でんわ]", en: "telephone", level: "N5" },
  { jp: "携帯[けいたい]", en: "mobile phone", level: "N5" },
  { jp: "テレビ", en: "television", level: "N5" },
  { jp: "ラジオ", en: "radio", level: "N5" },
  { jp: "コンピューター", en: "computer", level: "N5" },
  { jp: "パソコン", en: "personal computer", level: "N5" },
  { jp: "カメラ", en: "camera", level: "N5" },
  { jp: "時計[とけい]", en: "clock, watch", level: "N5" },
  { jp: "鞄[かばん]", en: "bag", level: "N5" },
  { jp: "財布[さいふ]", en: "wallet", level: "N5" },
  { jp: "傘[かさ]", en: "umbrella", level: "N5" },
  { jp: "石鹸[せっけん]", en: "soap", level: "N5" },
  { jp: "タオル", en: "towel", level: "N5" },
  { jp: "ハンカチ", en: "handkerchief", level: "N5" },
  { jp: "ティッシュ", en: "tissue", level: "N5" },
  { jp: "歯磨[はみが]き", en: "toothbrushing, toothpaste", level: "N5" },
  { jp: "冷蔵庫[れいぞうこ]", en: "refrigerator", level: "N5" },
  { jp: "洗濯機[せんたくき]", en: "washing machine", level: "N5" },
  { jp: "掃除機[そうじき]", en: "vacuum cleaner", level: "N5" },
  { jp: "ストーブ", en: "heater, stove", level: "N5" },
  { jp: "勉強[べんきょう]", en: "study", level: "N5" },
  { jp: "宿題[しゅくだい]", en: "homework", level: "N5" },
  { jp: "試験[しけん]", en: "exam", level: "N5" },
  { jp: "テスト", en: "test", level: "N5" },
  { jp: "授業[じゅぎょう]", en: "lesson, class", level: "N5" },
  { jp: "練習[れんしゅう]", en: "practice", level: "N5" },
  { jp: "問題[もんだい]", en: "problem, question", level: "N5" },
  { jp: "質問[しつもん]", en: "question", level: "N5" },
  { jp: "答[こた]え", en: "answer", level: "N5" },
  { jp: "意味[いみ]", en: "meaning", level: "N5" },
  { jp: "言葉[ことば]", en: "word, language", level: "N5" },
  { jp: "字[じ]", en: "letter, character", level: "N5" },
  { jp: "漢字[かんじ]", en: "kanji", level: "N5" },
  { jp: "平仮名[ひらがな]", en: "hiragana", level: "N5" },
  { jp: "片仮名[カタカナ]", en: "katakana", level: "N5" },
  { jp: "辞書[じしょ]", en: "dictionary", level: "N5" },
  { jp: "教科書[きょうかしょ]", en: "textbook", level: "N5" },
  { jp: "雑誌[ざっし]", en: "magazine", level: "N5" },
  { jp: "新聞[しんぶん]", en: "newspaper", level: "N5" },
  { jp: "紙[かみ]", en: "paper", level: "N5" },
  { jp: "手紙[てがみ]", en: "letter (mail)", level: "N5" },
  { jp: "葉書[はがき]", en: "postcard", level: "N5" },
  { jp: "切手[きって]", en: "postage stamp", level: "N5" },
  { jp: "封筒[ふうとう]", en: "envelope", level: "N5" },
  { jp: "鉛筆[えんぴつ]", en: "pencil", level: "N5" },
  { jp: "ペン", en: "pen", level: "N5" },
  { jp: "ボールペン", en: "ballpoint pen", level: "N5" },
  { jp: "万年筆[まんねんひつ]", en: "fountain pen", level: "N5" },
  { jp: "消[け]しゴム", en: "eraser", level: "N5" },
  { jp: "ノート", en: "notebook", level: "N5" },
  { jp: "黒板[こくばん]", en: "blackboard", level: "N5" },
  { jp: "仕事[しごと]", en: "work, job", level: "N5" },
  { jp: "英語[えいご]", en: "English (language)", level: "N5" },
  { jp: "日本語[にほんご]", en: "Japanese (language)", level: "N5" },
  { jp: "言語[げんご]", en: "language", level: "N5" },
  { jp: "話[はなし]", en: "story, talk", level: "N5" },
  { jp: "服[ふく]", en: "clothes", level: "N5" },
  { jp: "洋服[ようふく]", en: "Western clothing", level: "N5" },
  { jp: "着物[きもの]", en: "kimono, clothes", level: "N5" },
  { jp: "シャツ", en: "shirt", level: "N5" },
  { jp: "Tシャツ", en: "T-shirt", level: "N5" },
  { jp: "ズボン", en: "pants, trousers", level: "N5" },
  { jp: "スカート", en: "skirt", level: "N5" },
  { jp: "ワンピース", en: "dress, one-piece", level: "N5" },
  { jp: "セーター", en: "sweater", level: "N5" },
  { jp: "コート", en: "coat", level: "N5" },
  { jp: "上着[うわぎ]", en: "coat, jacket", level: "N5" },
  { jp: "背広[せびろ]", en: "business suit", level: "N5" },
  { jp: "ネクタイ", en: "necktie", level: "N5" },
  { jp: "帽子[ぼうし]", en: "hat", level: "N5" },
  { jp: "眼鏡[めがね]", en: "glasses", level: "N5" },
  { jp: "靴[くつ]", en: "shoes", level: "N5" },
  { jp: "靴下[くつした]", en: "socks", level: "N5" },
  { jp: "ポケット", en: "pocket", level: "N5" },
  { jp: "ボタン", en: "button", level: "N5" },
  { jp: "色[いろ]", en: "color", level: "N5" },
  { jp: "白[しろ]", en: "white", level: "N5" },
  { jp: "黒[くろ]", en: "black", level: "N5" },
  { jp: "赤[あか]", en: "red", level: "N5" },
  { jp: "青[あお]", en: "blue", level: "N5" },
  { jp: "黄色[きいろ]", en: "yellow", level: "N5" },
  { jp: "緑[みどり]", en: "green", level: "N5" },
  { jp: "茶色[ちゃいろ]", en: "brown", level: "N5" },
  { jp: "する", en: "to do", level: "N5" },
  { jp: "ある", en: "to exist (inanimate)", level: "N5" },
  { jp: "いる", en: "to exist (animate), to need", level: "N5" },
  { jp: "行[い]く", en: "to go", level: "N5" },
  { jp: "来[く]る", en: "to come", level: "N5" },
  { jp: "帰[かえ]る", en: "to return home", level: "N5" },
  { jp: "戻[もど]る", en: "to return, to come back", level: "N5" },
  { jp: "歩[ある]く", en: "to walk", level: "N5" },
  { jp: "走[はし]る", en: "to run", level: "N5" },
  { jp: "泳[およ]ぐ", en: "to swim", level: "N5" },
  { jp: "飛[と]ぶ", en: "to fly, to jump", level: "N5" },
  { jp: "上[あ]がる", en: "to go up, to rise", level: "N5" },
  { jp: "上[あ]げる", en: "to give, to raise", level: "N5" },
  { jp: "下[お]りる", en: "to get off, to descend", level: "N5" },
  { jp: "下[さ]がる", en: "to go down", level: "N5" },
  { jp: "出[で]る", en: "to leave, to exit", level: "N5" },
  { jp: "出[だ]す", en: "to take out, to send", level: "N5" },
  { jp: "入[はい]る", en: "to enter", level: "N5" },
  { jp: "入[い]れる", en: "to put in", level: "N5" },
  { jp: "乗[の]る", en: "to ride, to board", level: "N5" },
  { jp: "降[お]りる", en: "to get off (a vehicle)", level: "N5" },
  { jp: "起[お]きる", en: "to wake up, to get up", level: "N5" },
  { jp: "寝[ね]る", en: "to sleep, to go to bed", level: "N5" },
  { jp: "立[た]つ", en: "to stand", level: "N5" },
  { jp: "座[すわ]る", en: "to sit", level: "N5" },
  { jp: "休[やす]む", en: "to rest, to take time off", level: "N5" },
  { jp: "遊[あそ]ぶ", en: "to play, to hang out", level: "N5" },
  { jp: "働[はたら]く", en: "to work", level: "N5" },
  { jp: "勉強[べんきょう]する", en: "to study", level: "N5" },
  { jp: "教[おし]える", en: "to teach", level: "N5" },
  { jp: "習[なら]う", en: "to learn", level: "N5" },
  { jp: "覚[おぼ]える", en: "to remember", level: "N5" },
  { jp: "忘[わす]れる", en: "to forget", level: "N5" },
  { jp: "分[わ]かる", en: "to understand", level: "N5" },
  { jp: "知[し]る", en: "to know", level: "N5" },
  { jp: "考[かんが]える", en: "to think, to consider", level: "N5" },
  { jp: "思[おも]う", en: "to think, to feel", level: "N5" },
  { jp: "見[み]る", en: "to see, to watch", level: "N5" },
  { jp: "見[み]せる", en: "to show", level: "N5" },
  { jp: "聞[き]く", en: "to listen, to ask", level: "N5" },
  { jp: "話[はな]す", en: "to speak", level: "N5" },
  { jp: "言[い]う", en: "to say", level: "N5" },
  { jp: "読[よ]む", en: "to read", level: "N5" },
  { jp: "書[か]く", en: "to write", level: "N5" },
  { jp: "歌[うた]う", en: "to sing", level: "N5" },
  { jp: "踊[おど]る", en: "to dance", level: "N5" },
  { jp: "食[た]べる", en: "to eat", level: "N5" },
  { jp: "飲[の]む", en: "to drink", level: "N5" },
  { jp: "吸[す]う", en: "to inhale, to smoke", level: "N5" },
  { jp: "買[か]う", en: "to buy", level: "N5" },
  { jp: "売[う]る", en: "to sell", level: "N5" },
  { jp: "貸[か]す", en: "to lend", level: "N5" },
  { jp: "借[か]りる", en: "to borrow", level: "N5" },
  { jp: "返[かえ]す", en: "to return (something)", level: "N5" },
  { jp: "払[はら]う", en: "to pay", level: "N5" },
  { jp: "作[つく]る", en: "to make", level: "N5" },
  { jp: "使[つか]う", en: "to use", level: "N5" },
  { jp: "切[き]る", en: "to cut", level: "N5" },
  { jp: "開[あ]ける", en: "to open (something)", level: "N5" },
  { jp: "開[あ]く", en: "to open (intransitive)", level: "N5" },
  { jp: "閉[し]める", en: "to close (something)", level: "N5" },
  { jp: "閉[し]まる", en: "to close (intransitive)", level: "N5" },
  { jp: "始[はじ]める", en: "to begin (something)", level: "N5" },
  { jp: "始[はじ]まる", en: "to begin (intransitive)", level: "N5" },
  { jp: "終[お]わる", en: "to finish, to end", level: "N5" },
  { jp: "付[つ]ける", en: "to attach, to turn on", level: "N5" },
  { jp: "消[け]す", en: "to erase, to turn off", level: "N5" },
  { jp: "洗[あら]う", en: "to wash", level: "N5" },
  { jp: "掃除[そうじ]する", en: "to clean", level: "N5" },
  { jp: "洗濯[せんたく]する", en: "to do laundry", level: "N5" },
  { jp: "料理[りょうり]する", en: "to cook", level: "N5" },
  { jp: "撮[と]る", en: "to take (a photo)", level: "N5" },
  { jp: "取[と]る", en: "to take, to pick up", level: "N5" },
  { jp: "持[も]つ", en: "to hold, to have", level: "N5" },
  { jp: "渡[わた]す", en: "to hand over", level: "N5" },
  { jp: "渡[わた]る", en: "to cross", level: "N5" },
  { jp: "曲[ま]がる", en: "to turn, to bend", level: "N5" },
  { jp: "並[なら]ぶ", en: "to line up", level: "N5" },
  { jp: "並[なら]べる", en: "to arrange in a row", level: "N5" },
  { jp: "登[のぼ]る", en: "to climb", level: "N5" },
  { jp: "止[と]まる", en: "to stop (intransitive)", level: "N5" },
  { jp: "止[と]める", en: "to stop (something)", level: "N5" },
  { jp: "笑[わら]う", en: "to laugh, to smile", level: "N5" },
  { jp: "泣[な]く", en: "to cry", level: "N5" },
  { jp: "怒[おこ]る", en: "to get angry", level: "N5" },
  { jp: "死[し]ぬ", en: "to die", level: "N5" },
  { jp: "住[す]む", en: "to live, to reside", level: "N5" },
  { jp: "生[う]まれる", en: "to be born", level: "N5" },
  { jp: "結婚[けっこん]する", en: "to marry", level: "N5" },
  { jp: "旅行[りょこう]する", en: "to travel", level: "N5" },
  { jp: "散歩[さんぽ]する", en: "to take a walk", level: "N5" },
  { jp: "電話[でんわ]する", en: "to phone", level: "N5" },
  { jp: "コピーする", en: "to copy", level: "N5" },
  { jp: "招待[しょうたい]する", en: "to invite", level: "N5" },
  { jp: "答[こた]える", en: "to answer", level: "N5" },
  { jp: "頼[たの]む", en: "to request", level: "N5" },
  { jp: "貰[もら]う", en: "to receive", level: "N5" },
  { jp: "呉[く]れる", en: "to give (to me)", level: "N5" },
  { jp: "やる", en: "to do, to give", level: "N5" },
  { jp: "弾[ひ]く", en: "to play (instrument)", level: "N5" },
  { jp: "降[ふ]る", en: "to fall (rain/snow)", level: "N5" },
  { jp: "晴[は]れる", en: "to clear up (weather)", level: "N5" },
  { jp: "曇[くも]る", en: "to become cloudy", level: "N5" },
  { jp: "吹[ふ]く", en: "to blow (wind)", level: "N5" },
  { jp: "咲[さ]く", en: "to bloom", level: "N5" },
  { jp: "鳴[な]く", en: "to chirp, to cry (animal)", level: "N5" },
  { jp: "送[おく]る", en: "to send", level: "N5" },
  { jp: "出[で]かける", en: "to go out", level: "N5" },
  { jp: "着[き]る", en: "to wear (upper body)", level: "N5" },
  { jp: "脱[ぬ]ぐ", en: "to take off (clothes)", level: "N5" },
  { jp: "履[は]く", en: "to wear (lower body)", level: "N5" },
  { jp: "被[かぶ]る", en: "to wear (on head)", level: "N5" },
  { jp: "掛[か]ける", en: "to put on (glasses), to hang", level: "N5" },
  { jp: "急[いそ]ぐ", en: "to hurry", level: "N5" },
  { jp: "待[ま]つ", en: "to wait", level: "N5" },
  { jp: "会[あ]う", en: "to meet", level: "N5" },
  { jp: "迎[むか]える", en: "to greet, to welcome", level: "N5" },
  { jp: "押[お]す", en: "to push", level: "N5" },
  { jp: "引[ひ]く", en: "to pull", level: "N5" },
  { jp: "大[おお]きい", en: "big", level: "N5" },
  { jp: "小[ちい]さい", en: "small", level: "N5" },
  { jp: "新[あたら]しい", en: "new", level: "N5" },
  { jp: "古[ふる]い", en: "old (not for people)", level: "N5" },
  { jp: "高[たか]い", en: "expensive, tall", level: "N5" },
  { jp: "安[やす]い", en: "cheap", level: "N5" },
  { jp: "低[ひく]い", en: "low, short", level: "N5" },
  { jp: "良[い]い", en: "good", level: "N5" },
  { jp: "悪[わる]い", en: "bad", level: "N5" },
  { jp: "暑[あつ]い", en: "hot (weather)", level: "N5" },
  { jp: "寒[さむ]い", en: "cold (weather)", level: "N5" },
  { jp: "熱[あつ]い", en: "hot (to the touch)", level: "N5" },
  { jp: "冷[つめ]たい", en: "cold (to the touch)", level: "N5" },
  { jp: "暖[あたた]かい", en: "warm", level: "N5" },
  { jp: "涼[すず]しい", en: "cool", level: "N5" },
  { jp: "忙[いそが]しい", en: "busy", level: "N5" },
  { jp: "楽[たの]しい", en: "fun, enjoyable", level: "N5" },
  { jp: "嬉[うれ]しい", en: "happy", level: "N5" },
  { jp: "悲[かな]しい", en: "sad", level: "N5" },
  { jp: "面白[おもしろ]い", en: "interesting, funny", level: "N5" },
  { jp: "つまらない", en: "boring", level: "N5" },
  { jp: "難[むずか]しい", en: "difficult", level: "N5" },
  { jp: "易[やさ]しい", en: "easy, kind", level: "N5" },
  { jp: "優[やさ]しい", en: "kind, gentle", level: "N5" },
  { jp: "強[つよ]い", en: "strong", level: "N5" },
  { jp: "弱[よわ]い", en: "weak", level: "N5" },
  { jp: "長[なが]い", en: "long", level: "N5" },
  { jp: "短[みじか]い", en: "short", level: "N5" },
  { jp: "速[はや]い", en: "fast", level: "N5" },
  { jp: "早[はや]い", en: "early", level: "N5" },
  { jp: "遅[おそ]い", en: "slow, late", level: "N5" },
  { jp: "近[ちか]い", en: "near", level: "N5" },
  { jp: "遠[とお]い", en: "far", level: "N5" },
  { jp: "広[ひろ]い", en: "wide, spacious", level: "N5" },
  { jp: "狭[せま]い", en: "narrow, small", level: "N5" },
  { jp: "厚[あつ]い", en: "thick", level: "N5" },
  { jp: "薄[うす]い", en: "thin", level: "N5" },
  { jp: "重[おも]い", en: "heavy", level: "N5" },
  { jp: "軽[かる]い", en: "light (weight)", level: "N5" },
  { jp: "多[おお]い", en: "many", level: "N5" },
  { jp: "少[すく]ない", en: "few", level: "N5" },
  { jp: "明[あか]るい", en: "bright, cheerful", level: "N5" },
  { jp: "暗[くら]い", en: "dark, gloomy", level: "N5" },
  { jp: "甘[あま]い", en: "sweet", level: "N5" },
  { jp: "辛[から]い", en: "spicy, salty", level: "N5" },
  { jp: "美味[おい]しい", en: "delicious", level: "N5" },
  { jp: "不味[まず]い", en: "bad-tasting", level: "N5" },
  { jp: "汚[きたな]い", en: "dirty", level: "N5" },
  { jp: "白[しろ]い", en: "white", level: "N5" },
  { jp: "黒[くろ]い", en: "black", level: "N5" },
  { jp: "赤[あか]い", en: "red", level: "N5" },
  { jp: "青[あお]い", en: "blue", level: "N5" },
  { jp: "黄色[きいろ]い", en: "yellow", level: "N5" },
  { jp: "丸[まる]い", en: "round", level: "N5" },
  { jp: "若[わか]い", en: "young", level: "N5" },
  { jp: "可愛[かわい]い", en: "cute", level: "N5" },
  { jp: "痛[いた]い", en: "painful", level: "N5" },
  { jp: "危[あぶ]ない", en: "dangerous", level: "N5" },
  { jp: "無[な]い", en: "non-existent, not have", level: "N5" },
  { jp: "欲[ほ]しい", en: "want, desire", level: "N5" },
  { jp: "好[す]き", en: "liked, favorite", level: "N5" },
  { jp: "嫌[きら]い", en: "disliked", level: "N5" },
  { jp: "大好[だいす]き", en: "loved, favorite", level: "N5" },
  { jp: "大嫌[だいきら]い", en: "hated", level: "N5" },
  { jp: "上手[じょうず]", en: "skillful", level: "N5" },
  { jp: "下手[へた]", en: "unskillful", level: "N5" },
  { jp: "綺麗[きれい]", en: "pretty, clean", level: "N5" },
  { jp: "静[しず]か", en: "quiet", level: "N5" },
  { jp: "賑[にぎ]やか", en: "lively", level: "N5" },
  { jp: "便利[べんり]", en: "convenient", level: "N5" },
  { jp: "有名[ゆうめい]", en: "famous", level: "N5" },
  { jp: "親切[しんせつ]", en: "kind", level: "N5" },
  { jp: "暇[ひま]", en: "free (time)", level: "N5" },
  { jp: "色々[いろいろ]", en: "various", level: "N5" },
  { jp: "同[おな]じ", en: "same", level: "N5" },
  { jp: "大切[たいせつ]", en: "important", level: "N5" },
  { jp: "大変[たいへん]", en: "serious, very", level: "N5" },
  { jp: "結構[けっこう]", en: "fine, splendid", level: "N5" },
  { jp: "丈夫[じょうぶ]", en: "sturdy, healthy", level: "N5" },
  { jp: "立派[りっぱ]", en: "splendid, fine", level: "N5" },
  { jp: "もう", en: "already, soon", level: "N5" },
  { jp: "まだ", en: "still, not yet", level: "N5" },
  { jp: "また", en: "again", level: "N5" },
  { jp: "もっと", en: "more", level: "N5" },
  { jp: "ちょっと", en: "a little, a moment", level: "N5" },
  { jp: "少々[しょうしょう]", en: "a little, slightly", level: "N5" },
  { jp: "余[あま]り", en: "(not) very", level: "N5" },
  { jp: "とても", en: "very", level: "N5" },
  { jp: "本当[ほんとう]に", en: "really", level: "N5" },
  { jp: "全然[ぜんぜん]", en: "not at all", level: "N5" },
  { jp: "一緒[いっしょ]に", en: "together", level: "N5" },
  { jp: "一人[ひとり]で", en: "alone", level: "N5" },
  { jp: "直[す]ぐ", en: "immediately", level: "N5" },
  { jp: "ゆっくり", en: "slowly", level: "N5" },
  { jp: "大抵[たいてい]", en: "usually", level: "N5" },
  { jp: "時々[ときどき]", en: "sometimes", level: "N5" },
  { jp: "いつも", en: "always", level: "N5" },
  { jp: "よく", en: "often, well", level: "N5" },
  { jp: "初[はじ]めて", en: "for the first time", level: "N5" },
  { jp: "もう一度[いちど]", en: "once more", level: "N5" },
  { jp: "丁度[ちょうど]", en: "exactly, just", level: "N5" },
  { jp: "勿論[もちろん]", en: "of course", level: "N5" },
  { jp: "多分[たぶん]", en: "probably", level: "N5" },
  { jp: "段々[だんだん]", en: "gradually", level: "N5" },
  { jp: "ちょうど", en: "exactly", level: "N5" },
  { jp: "上[うえ]", en: "above, on", level: "N5" },
  { jp: "下[した]", en: "below, under", level: "N5" },
  { jp: "前[まえ]", en: "front, before", level: "N5" },
  { jp: "後[うし]ろ", en: "behind, back", level: "N5" },
  { jp: "右[みぎ]", en: "right", level: "N5" },
  { jp: "左[ひだり]", en: "left", level: "N5" },
  { jp: "中[なか]", en: "inside, middle", level: "N5" },
  { jp: "外[そと]", en: "outside", level: "N5" },
  { jp: "横[よこ]", en: "side, horizontal", level: "N5" },
  { jp: "そば", en: "near, beside", level: "N5" },
  { jp: "間[あいだ]", en: "between, during", level: "N5" },
  { jp: "東[ひがし]", en: "east", level: "N5" },
  { jp: "西[にし]", en: "west", level: "N5" },
  { jp: "南[みなみ]", en: "south", level: "N5" },
  { jp: "北[きた]", en: "north", level: "N5" },
  { jp: "向[むこ]う", en: "over there, the other side", level: "N5" },
  { jp: "何[なに]", en: "what", level: "N5" },
  { jp: "誰[だれ]", en: "who", level: "N5" },
  { jp: "何方[どなた]", en: "who (polite)", level: "N5" },
  { jp: "何処[どこ]", en: "where", level: "N5" },
  { jp: "何時[いつ]", en: "when", level: "N5" },
  { jp: "何故[なぜ]", en: "why", level: "N5" },
  { jp: "どうして", en: "why, how", level: "N5" },
  { jp: "どう", en: "how", level: "N5" },
  { jp: "どんな", en: "what kind of", level: "N5" },
  { jp: "どれ", en: "which one", level: "N5" },
  { jp: "どちら", en: "which (of two), where (polite)", level: "N5" },
  { jp: "これ", en: "this one", level: "N5" },
  { jp: "それ", en: "that one", level: "N5" },
  { jp: "あれ", en: "that one (over there)", level: "N5" },
  { jp: "この", en: "this", level: "N5" },
  { jp: "その", en: "that", level: "N5" },
  { jp: "あの", en: "that (over there)", level: "N5" },
  { jp: "ここ", en: "here", level: "N5" },
  { jp: "そこ", en: "there", level: "N5" },
  { jp: "あそこ", en: "over there", level: "N5" },
  { jp: "こちら", en: "this way, this person (polite)", level: "N5" },
  { jp: "そちら", en: "that way", level: "N5" },
  { jp: "あちら", en: "that way (over there)", level: "N5" },
  { jp: "こう", en: "in this way", level: "N5" },
  { jp: "そう", en: "in that way", level: "N5" },
  { jp: "ああ", en: "in that way (over there)", level: "N5" },
  { jp: "おはよう", en: "good morning (casual)", level: "N5" },
  { jp: "お早[はよ]うございます", en: "good morning", level: "N5" },
  { jp: "今日[こんにち]は", en: "hello, good afternoon", level: "N5" },
  { jp: "今晩[こんばん]は", en: "good evening", level: "N5" },
  { jp: "お休[やす]みなさい", en: "good night", level: "N5" },
  { jp: "さようなら", en: "goodbye", level: "N5" },
  { jp: "じゃあ", en: "well then, see you", level: "N5" },
  { jp: "有[あ]り難[がと]う", en: "thank you", level: "N5" },
  { jp: "どういたしまして", en: "you're welcome", level: "N5" },
  { jp: "済[す]みません", en: "excuse me, sorry", level: "N5" },
  { jp: "御免[ごめん]なさい", en: "I'm sorry", level: "N5" },
  { jp: "初[はじ]めまして", en: "nice to meet you", level: "N5" },
  { jp: "どうぞ", en: "please go ahead", level: "N5" },
  { jp: "どうも", en: "thanks, very much", level: "N5" },
  { jp: "頂[いただ]きます", en: "(said before eating)", level: "N5" },
  { jp: "御馳走様[ごちそうさま]", en: "thanks for the meal", level: "N5" },
  { jp: "行[い]ってきます", en: "I'm leaving (home)", level: "N5" },
  { jp: "行[い]ってらっしゃい", en: "go and come back", level: "N5" },
  { jp: "ただいま", en: "I'm home", level: "N5" },
  { jp: "お帰[かえ]りなさい", en: "welcome home", level: "N5" },
  { jp: "お願[ねが]いします", en: "please", level: "N5" },
  { jp: "失礼[しつれい]します", en: "excuse me / pardon me", level: "N5" },
  { jp: "はい", en: "yes", level: "N5" },
  { jp: "いいえ", en: "no", level: "N5" },
  { jp: "そして", en: "and then", level: "N5" },
  { jp: "それから", en: "after that", level: "N5" },
  { jp: "でも", en: "but, however", level: "N5" },
  { jp: "しかし", en: "however", level: "N5" },
  { jp: "じゃ", en: "well then", level: "N5" },
  { jp: "では", en: "well then", level: "N5" },
  { jp: "もしもし", en: "hello (on phone)", level: "N5" },
  { jp: "社会[しゃかい]", en: "society", level: "N4" },
  { jp: "世界[せかい]", en: "world", level: "N4" },
  { jp: "文化[ぶんか]", en: "culture", level: "N4" },
  { jp: "文学[ぶんがく]", en: "literature", level: "N4" },
  { jp: "歴史[れきし]", en: "history", level: "N4" },
  { jp: "地理[ちり]", en: "geography", level: "N4" },
  { jp: "科学[かがく]", en: "science", level: "N4" },
  { jp: "数学[すうがく]", en: "mathematics", level: "N4" },
  { jp: "政治[せいじ]", en: "politics", level: "N4" },
  { jp: "経済[けいざい]", en: "economy", level: "N4" },
  { jp: "産業[さんぎょう]", en: "industry", level: "N4" },
  { jp: "国際[こくさい]", en: "international", level: "N4" },
  { jp: "戦争[せんそう]", en: "war", level: "N4" },
  { jp: "平和[へいわ]", en: "peace", level: "N4" },
  { jp: "法律[ほうりつ]", en: "law", level: "N4" },
  { jp: "規則[きそく]", en: "rule, regulation", level: "N4" },
  { jp: "宗教[しゅうきょう]", en: "religion", level: "N4" },
  { jp: "教育[きょういく]", en: "education", level: "N4" },
  { jp: "市民[しみん]", en: "citizen", level: "N4" },
  { jp: "国民[こくみん]", en: "nation, citizen", level: "N4" },
  { jp: "人口[じんこう]", en: "population", level: "N4" },
  { jp: "会議[かいぎ]", en: "meeting", level: "N4" },
  { jp: "会場[かいじょう]", en: "meeting place, venue", level: "N4" },
  { jp: "受付[うけつけ]", en: "reception desk", level: "N4" },
  { jp: "案内[あんない]", en: "guidance, information", level: "N4" },
  { jp: "場所[ばしょ]", en: "place, location", level: "N4" },
  { jp: "席[せき]", en: "seat", level: "N4" },
  { jp: "用事[ようじ]", en: "errand, business", level: "N4" },
  { jp: "予定[よてい]", en: "plan, schedule", level: "N4" },
  { jp: "計画[けいかく]", en: "plan, project", level: "N4" },
  { jp: "準備[じゅんび]", en: "preparation", level: "N4" },
  { jp: "用意[ようい]", en: "preparation, arrangements", level: "N4" },
  { jp: "予約[よやく]", en: "reservation", level: "N4" },
  { jp: "約束[やくそく]", en: "promise, appointment", level: "N4" },
  { jp: "返事[へんじ]", en: "reply", level: "N4" },
  { jp: "連絡[れんらく]", en: "contact, communication", level: "N4" },
  { jp: "相談[そうだん]", en: "consultation", level: "N4" },
  { jp: "意見[いけん]", en: "opinion", level: "N4" },
  { jp: "理由[りゆう]", en: "reason", level: "N4" },
  { jp: "原因[げんいん]", en: "cause", level: "N4" },
  { jp: "結果[けっか]", en: "result", level: "N4" },
  { jp: "目的[もくてき]", en: "purpose", level: "N4" },
  { jp: "経験[けいけん]", en: "experience", level: "N4" },
  { jp: "説明[せつめい]", en: "explanation", level: "N4" },
  { jp: "紹介[しょうかい]", en: "introduction", level: "N4" },
  { jp: "報告[ほうこく]", en: "report", level: "N4" },
  { jp: "場合[ばあい]", en: "case, situation", level: "N4" },
  { jp: "様子[ようす]", en: "appearance, state", level: "N4" },
  { jp: "気持[きも]ち", en: "feeling, mood", level: "N4" },
  { jp: "気分[きぶん]", en: "feeling, mood", level: "N4" },
  { jp: "都合[つごう]", en: "convenience, circumstances", level: "N4" },
  { jp: "趣味[しゅみ]", en: "hobby", level: "N4" },
  { jp: "興味[きょうみ]", en: "interest", level: "N4" },
  { jp: "夢[ゆめ]", en: "dream", level: "N4" },
  { jp: "考[かんが]え", en: "thought, idea", level: "N4" },
  { jp: "心[こころ]", en: "heart, mind", level: "N4" },
  { jp: "命[いのち]", en: "life", level: "N4" },
  { jp: "人生[じんせい]", en: "(human) life", level: "N4" },
  { jp: "生活[せいかつ]", en: "daily life", level: "N4" },
  { jp: "習慣[しゅうかん]", en: "custom, habit", level: "N4" },
  { jp: "性格[せいかく]", en: "personality", level: "N4" },
  { jp: "才能[さいのう]", en: "talent", level: "N4" },
  { jp: "力[ちから]", en: "power, strength", level: "N4" },
  { jp: "事業[じぎょう]", en: "enterprise, business", level: "N4" },
  { jp: "工業[こうぎょう]", en: "industry", level: "N4" },
  { jp: "農業[のうぎょう]", en: "agriculture", level: "N4" },
  { jp: "営業[えいぎょう]", en: "business, sales", level: "N4" },
  { jp: "工場[こうじょう]", en: "factory", level: "N4" },
  { jp: "支店[してん]", en: "branch (office)", level: "N4" },
  { jp: "事務[じむ]", en: "office work", level: "N4" },
  { jp: "技術[ぎじゅつ]", en: "technology, skill", level: "N4" },
  { jp: "機械[きかい]", en: "machine", level: "N4" },
  { jp: "道具[どうぐ]", en: "tool", level: "N4" },
  { jp: "材料[ざいりょう]", en: "materials, ingredients", level: "N4" },
  { jp: "原料[げんりょう]", en: "raw materials", level: "N4" },
  { jp: "製品[せいひん]", en: "product", level: "N4" },
  { jp: "商品[しょうひん]", en: "merchandise", level: "N4" },
  { jp: "品物[しなもの]", en: "goods, article", level: "N4" },
  { jp: "輸出[ゆしゅつ]", en: "export", level: "N4" },
  { jp: "輸入[ゆにゅう]", en: "import", level: "N4" },
  { jp: "貿易[ぼうえき]", en: "trade", level: "N4" },
  { jp: "値段[ねだん]", en: "price", level: "N4" },
  { jp: "料金[りょうきん]", en: "fee, charge", level: "N4" },
  { jp: "代金[だいきん]", en: "price, charge", level: "N4" },
  { jp: "税金[ぜいきん]", en: "tax", level: "N4" },
  { jp: "給料[きゅうりょう]", en: "salary", level: "N4" },
  { jp: "貯金[ちょきん]", en: "savings", level: "N4" },
  { jp: "お金持[かねも]ち", en: "wealthy person", level: "N4" },
  { jp: "お釣[つ]り", en: "change (money)", level: "N4" },
  { jp: "お札[さつ]", en: "bill, banknote", level: "N4" },
  { jp: "小銭[こぜに]", en: "small change, coins", level: "N4" },
  { jp: "売店[ばいてん]", en: "kiosk, stand", level: "N4" },
  { jp: "売場[うりば]", en: "sales floor", level: "N4" },
  { jp: "客[きゃく]", en: "customer, guest", level: "N4" },
  { jp: "お客[きゃく]さん", en: "customer (polite)", level: "N4" },
  { jp: "店長[てんちょう]", en: "store manager", level: "N4" },
  { jp: "社長[しゃちょう]", en: "company president", level: "N4" },
  { jp: "部長[ぶちょう]", en: "department head", level: "N4" },
  { jp: "課長[かちょう]", en: "section chief", level: "N4" },
  { jp: "同僚[どうりょう]", en: "colleague", level: "N4" },
  { jp: "職業[しょくぎょう]", en: "occupation", level: "N4" },
  { jp: "アルバイト", en: "part-time job", level: "N4" },
  { jp: "残業[ざんぎょう]", en: "overtime", level: "N4" },
  { jp: "出張[しゅっちょう]", en: "business trip", level: "N4" },
  { jp: "退院[たいいん]", en: "leaving hospital", level: "N4" },
  { jp: "入院[にゅういん]", en: "hospitalization", level: "N4" },
  { jp: "入学[にゅうがく]", en: "school entrance", level: "N4" },
  { jp: "卒業[そつぎょう]", en: "graduation", level: "N4" },
  { jp: "試合[しあい]", en: "match, game", level: "N4" },
  { jp: "競争[きょうそう]", en: "competition", level: "N4" },
  { jp: "優勝[ゆうしょう]", en: "championship, victory", level: "N4" },
  { jp: "交通[こうつう]", en: "traffic, transportation", level: "N4" },
  { jp: "運転[うんてん]", en: "driving", level: "N4" },
  { jp: "運転手[うんてんしゅ]", en: "driver", level: "N4" },
  { jp: "事故[じこ]", en: "accident", level: "N4" },
  { jp: "故障[こしょう]", en: "breakdown, malfunction", level: "N4" },
  { jp: "渋滞[じゅうたい]", en: "traffic jam", level: "N4" },
  { jp: "踏切[ふみきり]", en: "railroad crossing", level: "N4" },
  { jp: "歩道[ほどう]", en: "sidewalk", level: "N4" },
  { jp: "横断歩道[おうだんほどう]", en: "pedestrian crossing", level: "N4" },
  { jp: "高速道路[こうそくどうろ]", en: "highway", level: "N4" },
  { jp: "駐車場[ちゅうしゃじょう]", en: "parking lot", level: "N4" },
  { jp: "ガソリン", en: "gasoline", level: "N4" },
  { jp: "ガソリンスタンド", en: "gas station", level: "N4" },
  { jp: "通り[とおり]", en: "street, avenue", level: "N4" },
  { jp: "船便[ふなびん]", en: "surface mail, sea mail", level: "N4" },
  { jp: "港[みなと]", en: "harbor, port", level: "N4" },
  { jp: "指定席[していせき]", en: "reserved seat", level: "N4" },
  { jp: "自由席[じゆうせき]", en: "non-reserved seat", level: "N4" },
  { jp: "片道[かたみち]", en: "one-way", level: "N4" },
  { jp: "往復[おうふく]", en: "round trip", level: "N4" },
  { jp: "急行[きゅうこう]", en: "express train", level: "N4" },
  { jp: "特急[とっきゅう]", en: "limited express", level: "N4" },
  { jp: "普通[ふつう]", en: "local train; usual", level: "N4" },
  { jp: "観光[かんこう]", en: "sightseeing", level: "N4" },
  { jp: "見物[けんぶつ]", en: "sightseeing", level: "N4" },
  { jp: "旅館[りょかん]", en: "Japanese inn", level: "N4" },
  { jp: "民宿[みんしゅく]", en: "guest house, B&B", level: "N4" },
  { jp: "土産[みやげ]", en: "souvenir", level: "N4" },
  { jp: "お土産[みやげ]", en: "souvenir (polite)", level: "N4" },
  { jp: "荷物[にもつ]", en: "luggage", level: "N4" },
  { jp: "航空便[こうくうびん]", en: "airmail", level: "N4" },
  { jp: "小包[こづつみ]", en: "package, parcel", level: "N4" },
  { jp: "宅配便[たくはいびん]", en: "home delivery", level: "N4" },
  { jp: "郊外[こうがい]", en: "suburbs", level: "N4" },
  { jp: "都会[とかい]", en: "city, urban area", level: "N4" },
  { jp: "田舎[いなか]", en: "countryside", level: "N4" },
  { jp: "村[むら]", en: "village", level: "N4" },
  { jp: "島[しま]", en: "island", level: "N4" },
  { jp: "県[けん]", en: "prefecture", level: "N4" },
  { jp: "都[と]", en: "metropolis", level: "N4" },
  { jp: "府[ふ]", en: "urban prefecture", level: "N4" },
  { jp: "区[く]", en: "ward", level: "N4" },
  { jp: "工事[こうじ]", en: "construction", level: "N4" },
  { jp: "周[まわ]り", en: "surroundings", level: "N4" },
  { jp: "辺[へん]", en: "area, vicinity", level: "N4" },
  { jp: "途中[とちゅう]", en: "on the way", level: "N4" },
  { jp: "屋上[おくじょう]", en: "rooftop", level: "N4" },
  { jp: "地下[ちか]", en: "underground", level: "N4" },
  { jp: "美容院[びよういん]", en: "beauty salon", level: "N4" },
  { jp: "床屋[とこや]", en: "barbershop", level: "N4" },
  { jp: "歯医者[はいしゃ]", en: "dentist", level: "N4" },
  { jp: "寺[てら]", en: "Buddhist temple", level: "N4" },
  { jp: "神社[じんじゃ]", en: "Shinto shrine", level: "N4" },
  { jp: "教会[きょうかい]", en: "church", level: "N4" },
  { jp: "城[しろ]", en: "castle", level: "N4" },
  { jp: "祭[まつ]り", en: "festival", level: "N4" },
  { jp: "指[ゆび]", en: "finger", level: "N4" },
  { jp: "爪[つめ]", en: "fingernail", level: "N4" },
  { jp: "腕[うで]", en: "arm", level: "N4" },
  { jp: "肩[かた]", en: "shoulder", level: "N4" },
  { jp: "胸[むね]", en: "chest", level: "N4" },
  { jp: "背中[せなか]", en: "back", level: "N4" },
  { jp: "腰[こし]", en: "lower back, hip", level: "N4" },
  { jp: "膝[ひざ]", en: "knee", level: "N4" },
  { jp: "髭[ひげ]", en: "beard, moustache", level: "N4" },
  { jp: "皮膚[ひふ]", en: "skin", level: "N4" },
  { jp: "血[ち]", en: "blood", level: "N4" },
  { jp: "怪我[けが]", en: "injury", level: "N4" },
  { jp: "火傷[やけど]", en: "burn", level: "N4" },
  { jp: "注射[ちゅうしゃ]", en: "injection", level: "N4" },
  { jp: "手術[しゅじゅつ]", en: "surgery", level: "N4" },
  { jp: "看護師[かんごし]", en: "nurse", level: "N4" },
  { jp: "感[かん]じ", en: "feeling, impression", level: "N4" },
  { jp: "笑顔[えがお]", en: "smile", level: "N4" },
  { jp: "涙[なみだ]", en: "tear", level: "N4" },
  { jp: "嘘[うそ]", en: "lie, falsehood", level: "N4" },
  { jp: "本当[ほんとう]", en: "truth, really", level: "N4" },
  { jp: "間違[まちが]い", en: "mistake", level: "N4" },
  { jp: "失敗[しっぱい]", en: "failure", level: "N4" },
  { jp: "成功[せいこう]", en: "success", level: "N4" },
  { jp: "予[よ]報", en: "forecast", level: "N4" },
  { jp: "天気予報[てんきよほう]", en: "weather forecast", level: "N4" },
  { jp: "インターネット", en: "internet", level: "N4" },
  { jp: "メール", en: "email", level: "N4" },
  { jp: "ホームページ", en: "website", level: "N4" },
  { jp: "アドレス", en: "address (email/web)", level: "N4" },
  { jp: "ファックス", en: "fax", level: "N4" },
  { jp: "番組[ばんぐみ]", en: "TV program", level: "N4" },
  { jp: "ニュース", en: "news", level: "N4" },
  { jp: "アニメ", en: "anime", level: "N4" },
  { jp: "漫画[まんが]", en: "comic, manga", level: "N4" },
  { jp: "小説[しょうせつ]", en: "novel", level: "N4" },
  { jp: "音楽[おんがく]", en: "music", level: "N4" },
  { jp: "歌[うた]", en: "song", level: "N4" },
  { jp: "ピアノ", en: "piano", level: "N4" },
  { jp: "ギター", en: "guitar", level: "N4" },
  { jp: "踊[おど]り", en: "dance", level: "N4" },
  { jp: "絵[え]", en: "picture, painting", level: "N4" },
  { jp: "写真[しゃしん]", en: "photo", level: "N4" },
  { jp: "ゲーム", en: "game", level: "N4" },
  { jp: "玩具[おもちゃ]", en: "toy", level: "N4" },
  { jp: "人形[にんぎょう]", en: "doll", level: "N4" },
  { jp: "プレゼント", en: "present, gift", level: "N4" },
  { jp: "贈[おく]り物[もの]", en: "gift", level: "N4" },
  { jp: "袋[ふくろ]", en: "bag, sack", level: "N4" },
  { jp: "箱[はこ]", en: "box", level: "N4" },
  { jp: "瓶[びん]", en: "bottle", level: "N4" },
  { jp: "缶[かん]", en: "can", level: "N4" },
  { jp: "棚[たな]", en: "shelf", level: "N4" },
  { jp: "引[ひ]き出[だ]し", en: "drawer", level: "N4" },
  { jp: "鏡[かがみ]", en: "mirror", level: "N4" },
  { jp: "布団[ふとん]", en: "futon, bedding", level: "N4" },
  { jp: "毛布[もうふ]", en: "blanket", level: "N4" },
  { jp: "枕[まくら]", en: "pillow", level: "N4" },
  { jp: "蓋[ふた]", en: "lid, cover", level: "N4" },
  { jp: "糸[いと]", en: "thread", level: "N4" },
  { jp: "針[はり]", en: "needle", level: "N4" },
  { jp: "紐[ひも]", en: "string, cord", level: "N4" },
  { jp: "ガラス", en: "glass (material)", level: "N4" },
  { jp: "プラスチック", en: "plastic", level: "N4" },
  { jp: "木[もく]", en: "wood (material)", level: "N4" },
  { jp: "金[きん]", en: "gold", level: "N4" },
  { jp: "銀[ぎん]", en: "silver", level: "N4" },
  { jp: "鉄[てつ]", en: "iron", level: "N4" },
  { jp: "石油[せきゆ]", en: "petroleum, oil", level: "N4" },
  { jp: "ガス", en: "gas", level: "N4" },
  { jp: "電池[でんち]", en: "battery", level: "N4" },
  { jp: "電灯[でんとう]", en: "electric light", level: "N4" },
  { jp: "スイッチ", en: "switch", level: "N4" },
  { jp: "続[つづ]ける", en: "to continue (something)", level: "N4" },
  { jp: "続[つづ]く", en: "to continue (intransitive)", level: "N4" },
  { jp: "止[や]める", en: "to quit, to stop doing", level: "N4" },
  { jp: "決[き]める", en: "to decide", level: "N4" },
  { jp: "決[き]まる", en: "to be decided", level: "N4" },
  { jp: "選[えら]ぶ", en: "to choose", level: "N4" },
  { jp: "比[くら]べる", en: "to compare", level: "N4" },
  { jp: "調[しら]べる", en: "to investigate, to check", level: "N4" },
  { jp: "確[たし]かめる", en: "to verify, to make sure", level: "N4" },
  { jp: "試[ため]す", en: "to try, to test", level: "N4" },
  { jp: "計算[けいさん]する", en: "to calculate", level: "N4" },
  { jp: "数[かぞ]える", en: "to count", level: "N4" },
  { jp: "増[ふ]える", en: "to increase (intransitive)", level: "N4" },
  { jp: "減[へ]る", en: "to decrease (intransitive)", level: "N4" },
  { jp: "変[か]わる", en: "to change (intransitive)", level: "N4" },
  { jp: "変[か]える", en: "to change (something)", level: "N4" },
  { jp: "直[なお]す", en: "to fix, to correct", level: "N4" },
  { jp: "直[なお]る", en: "to be fixed, to recover", level: "N4" },
  { jp: "治[なお]す", en: "to cure", level: "N4" },
  { jp: "治[なお]る", en: "to be cured", level: "N4" },
  { jp: "壊[こわ]す", en: "to break (something)", level: "N4" },
  { jp: "壊[こわ]れる", en: "to break (intransitive)", level: "N4" },
  { jp: "落[お]とす", en: "to drop, to lose", level: "N4" },
  { jp: "落[お]ちる", en: "to fall, to drop (intransitive)", level: "N4" },
  { jp: "見[み]つける", en: "to find (something)", level: "N4" },
  { jp: "見[み]つかる", en: "to be found", level: "N4" },
  { jp: "探[さが]す", en: "to search for", level: "N4" },
  { jp: "拾[ひろ]う", en: "to pick up", level: "N4" },
  { jp: "捨[す]てる", en: "to throw away", level: "N4" },
  { jp: "片付[かたづ]ける", en: "to tidy up", level: "N4" },
  { jp: "集[あつ]める", en: "to collect, to gather", level: "N4" },
  { jp: "集[あつ]まる", en: "to gather (intransitive)", level: "N4" },
  { jp: "配[くば]る", en: "to distribute", level: "N4" },
  { jp: "運[はこ]ぶ", en: "to carry, to transport", level: "N4" },
  { jp: "包[つつ]む", en: "to wrap", level: "N4" },
  { jp: "畳[たた]む", en: "to fold", level: "N4" },
  { jp: "受[う]ける", en: "to receive, to take (exam)", level: "N4" },
  { jp: "受[う]け取[と]る", en: "to receive, to accept", level: "N4" },
  { jp: "差[さ]し上[あ]げる", en: "to give (humble)", level: "N4" },
  { jp: "頂[いただ]く", en: "to receive (humble)", level: "N4" },
  { jp: "下[くだ]さる", en: "to give (honorific)", level: "N4" },
  { jp: "申[もう]す", en: "to say (humble)", level: "N4" },
  { jp: "申[もう]し上[あ]げる", en: "to say (very humble)", level: "N4" },
  { jp: "仰[おっしゃ]る", en: "to say (honorific)", level: "N4" },
  { jp: "致[いた]す", en: "to do (humble)", level: "N4" },
  { jp: "為[なさ]る", en: "to do (honorific)", level: "N4" },
  { jp: "御覧[ごらん]になる", en: "to see (honorific)", level: "N4" },
  { jp: "召[め]し上[あ]がる", en: "to eat (honorific)", level: "N4" },
  { jp: "伺[うかが]う", en: "to ask/visit (humble)", level: "N4" },
  { jp: "参[まい]る", en: "to come/go (humble)", level: "N4" },
  { jp: "いらっしゃる", en: "to be/come/go (honorific)", level: "N4" },
  { jp: "存[ぞん]じる", en: "to know/think (humble)", level: "N4" },
  { jp: "御存知[ごぞんじ]", en: "knowing (honorific)", level: "N4" },
  { jp: "誘[さそ]う", en: "to invite", level: "N4" },
  { jp: "祝[いわ]う", en: "to celebrate", level: "N4" },
  { jp: "贈[おく]る", en: "to give, to present", level: "N4" },
  { jp: "預[あず]ける", en: "to entrust, to deposit", level: "N4" },
  { jp: "預[あず]かる", en: "to take care of, to keep", level: "N4" },
  { jp: "残[のこ]る", en: "to remain", level: "N4" },
  { jp: "残[のこ]す", en: "to leave behind", level: "N4" },
  { jp: "余[あま]る", en: "to be left over", level: "N4" },
  { jp: "足[た]りる", en: "to be sufficient", level: "N4" },
  { jp: "間[ま]に合[あ]う", en: "to be in time", level: "N4" },
  { jp: "遅[おく]れる", en: "to be late", level: "N4" },
  { jp: "焦[あせ]る", en: "to feel rushed, to panic", level: "N4" },
  { jp: "驚[おどろ]く", en: "to be surprised", level: "N4" },
  { jp: "喜[よろこ]ぶ", en: "to be glad", level: "N4" },
  { jp: "悲[かな]しむ", en: "to be sad", level: "N4" },
  { jp: "困[こま]る", en: "to be troubled", level: "N4" },
  { jp: "心配[しんぱい]する", en: "to worry", level: "N4" },
  { jp: "安心[あんしん]する", en: "to feel relieved", level: "N4" },
  { jp: "感[かん]じる", en: "to feel", level: "N4" },
  { jp: "気[き]がつく", en: "to notice", level: "N4" },
  { jp: "気[き]にする", en: "to mind, to care about", level: "N4" },
  { jp: "謝[あやま]る", en: "to apologize", level: "N4" },
  { jp: "褒[ほ]める", en: "to praise", level: "N4" },
  { jp: "叱[しか]る", en: "to scold", level: "N4" },
  { jp: "守[まも]る", en: "to protect, to obey", level: "N4" },
  { jp: "助[たす]ける", en: "to help, to save", level: "N4" },
  { jp: "手伝[てつだ]う", en: "to help out", level: "N4" },
  { jp: "世話[せわ]する", en: "to take care of", level: "N4" },
  { jp: "育[そだ]てる", en: "to raise, to bring up", level: "N4" },
  { jp: "育[そだ]つ", en: "to grow up", level: "N4" },
  { jp: "成長[せいちょう]する", en: "to grow", level: "N4" },
  { jp: "勝[か]つ", en: "to win", level: "N4" },
  { jp: "負[ま]ける", en: "to lose, to be defeated", level: "N4" },
  { jp: "戦[たたか]う", en: "to fight", level: "N4" },
  { jp: "喧嘩[けんか]する", en: "to quarrel", level: "N4" },
  { jp: "盗[ぬす]む", en: "to steal", level: "N4" },
  { jp: "捕[つか]まえる", en: "to catch", level: "N4" },
  { jp: "逃[に]げる", en: "to escape", level: "N4" },
  { jp: "止[や]む", en: "to cease, to stop", level: "N4" },
  { jp: "通[かよ]う", en: "to commute", level: "N4" },
  { jp: "通[とお]る", en: "to pass through", level: "N4" },
  { jp: "通[とお]す", en: "to let through", level: "N4" },
  { jp: "進[すす]む", en: "to advance", level: "N4" },
  { jp: "戻[もど]す", en: "to put back", level: "N4" },
  { jp: "向[む]かう", en: "to head toward", level: "N4" },
  { jp: "向[む]く", en: "to face", level: "N4" },
  { jp: "回[まわ]る", en: "to turn, to go around", level: "N4" },
  { jp: "回[まわ]す", en: "to turn (something)", level: "N4" },
  { jp: "動[うご]く", en: "to move (intransitive)", level: "N4" },
  { jp: "動[うご]かす", en: "to move (something)", level: "N4" },
  { jp: "震[ふる]える", en: "to tremble", level: "N4" },
  { jp: "揺[ゆ]れる", en: "to shake, to sway", level: "N4" },
  { jp: "光[ひか]る", en: "to shine", level: "N4" },
  { jp: "燃[も]える", en: "to burn (intransitive)", level: "N4" },
  { jp: "冷[ひ]える", en: "to grow cold", level: "N4" },
  { jp: "冷[ひ]やす", en: "to chill, to cool", level: "N4" },
  { jp: "温[あたた]める", en: "to warm up", level: "N4" },
  { jp: "沸[わ]かす", en: "to boil (water)", level: "N4" },
  { jp: "沸[わ]く", en: "to come to a boil", level: "N4" },
  { jp: "焼[や]く", en: "to bake, to grill, to burn", level: "N4" },
  { jp: "焼[や]ける", en: "to be burnt, to be grilled", level: "N4" },
  { jp: "煮[に]る", en: "to simmer, to boil", level: "N4" },
  { jp: "茹[ゆ]でる", en: "to boil (food)", level: "N4" },
  { jp: "炊[た]く", en: "to cook (rice)", level: "N4" },
  { jp: "漬[つ]ける", en: "to soak, to pickle", level: "N4" },
  { jp: "混[ま]ぜる", en: "to mix", level: "N4" },
  { jp: "注[つ]ぐ", en: "to pour", level: "N4" },
  { jp: "塗[ぬ]る", en: "to paint, to spread", level: "N4" },
  { jp: "建[た]てる", en: "to build", level: "N4" },
  { jp: "建[た]つ", en: "to be built", level: "N4" },
  { jp: "植[う]える", en: "to plant", level: "N4" },
  { jp: "釣[つ]る", en: "to fish", level: "N4" },
  { jp: "祈[いの]る", en: "to pray", level: "N4" },
  { jp: "信[しん]じる", en: "to believe", level: "N4" },
  { jp: "疑[うたが]う", en: "to doubt", level: "N4" },
  { jp: "認[みと]める", en: "to recognize, to admit", level: "N4" },
  { jp: "許[ゆる]す", en: "to forgive, to permit", level: "N4" },
  { jp: "禁止[きんし]する", en: "to prohibit", level: "N4" },
  { jp: "注意[ちゅうい]する", en: "to be careful, to warn", level: "N4" },
  { jp: "気[き]を付[つ]ける", en: "to be careful", level: "N4" },
  { jp: "我慢[がまん]する", en: "to endure", level: "N4" },
  { jp: "頑張[がんば]る", en: "to do one's best", level: "N4" },
  { jp: "暮[く]らす", en: "to live, to get along", level: "N4" },
  { jp: "知[し]り合[あ]う", en: "to get acquainted", level: "N4" },
  { jp: "別[わか]れる", en: "to part, to separate", level: "N4" },
  { jp: "離[はな]れる", en: "to be separated from", level: "N4" },
  { jp: "繋[つな]ぐ", en: "to connect", level: "N4" },
  { jp: "踏[ふ]む", en: "to step on", level: "N4" },
  { jp: "叩[たた]く", en: "to hit, to knock", level: "N4" },
  { jp: "蹴[け]る", en: "to kick", level: "N4" },
  { jp: "投[な]げる", en: "to throw", level: "N4" },
  { jp: "掴[つか]む", en: "to grab", level: "N4" },
  { jp: "握[にぎ]る", en: "to grasp", level: "N4" },
  { jp: "抱[だ]く", en: "to hug, to hold", level: "N4" },
  { jp: "触[さわ]る", en: "to touch", level: "N4" },
  { jp: "舐[な]める", en: "to lick", level: "N4" },
  { jp: "噛[か]む", en: "to bite, to chew", level: "N4" },
  { jp: "吐[は]く", en: "to vomit, to exhale", level: "N4" },
  { jp: "汗[あせ]をかく", en: "to sweat", level: "N4" },
  { jp: "息[いき]をする", en: "to breathe", level: "N4" },
  { jp: "夢[ゆめ]を見[み]る", en: "to dream", level: "N4" },
  { jp: "気[き]がする", en: "to have a feeling", level: "N4" },
  { jp: "寂[さび]しい", en: "lonely", level: "N4" },
  { jp: "懐[なつ]かしい", en: "nostalgic, dear", level: "N4" },
  { jp: "恥[は]ずかしい", en: "embarrassing, shy", level: "N4" },
  { jp: "怖[こわ]い", en: "scary, afraid", level: "N4" },
  { jp: "厳[きび]しい", en: "strict, harsh", level: "N4" },
  { jp: "苦[くる]しい", en: "painful, distressing", level: "N4" },
  { jp: "苦[にが]い", en: "bitter", level: "N4" },
  { jp: "酸[す]っぱい", en: "sour", level: "N4" },
  { jp: "渋[しぶ]い", en: "astringent, tasteful", level: "N4" },
  { jp: "うまい", en: "skillful, delicious", level: "N4" },
  { jp: "細[こま]かい", en: "fine, small, detailed", level: "N4" },
  { jp: "細[ほそ]い", en: "thin, slender", level: "N4" },
  { jp: "太[ふと]い", en: "thick, fat", level: "N4" },
  { jp: "深[ふか]い", en: "deep", level: "N4" },
  { jp: "浅[あさ]い", en: "shallow", level: "N4" },
  { jp: "硬[かた]い", en: "hard, firm", level: "N4" },
  { jp: "柔[やわ]らかい", en: "soft", level: "N4" },
  { jp: "珍[めずら]しい", en: "rare, unusual", level: "N4" },
  { jp: "素晴[すば]らしい", en: "wonderful", level: "N4" },
  { jp: "美[うつく]しい", en: "beautiful", level: "N4" },
  { jp: "正[ただ]しい", en: "correct, right", level: "N4" },
  { jp: "詳[くわ]しい", en: "detailed, knowledgeable", level: "N4" },
  { jp: "酷[ひど]い", en: "terrible, cruel", level: "N4" },
  { jp: "嫌[いや]", en: "unpleasant, disagreeable", level: "N4" },
  { jp: "煩[うるさ]い", en: "noisy, annoying", level: "N4" },
  { jp: "眠[ねむ]い", en: "sleepy", level: "N4" },
  { jp: "凄[すご]い", en: "amazing, terrible", level: "N4" },
  { jp: "緩[ゆる]い", en: "loose, lax", level: "N4" },
  { jp: "おかしい", en: "strange, funny", level: "N4" },
  { jp: "可笑[おか]しい", en: "funny, strange", level: "N4" },
  { jp: "鋭[するど]い", en: "sharp", level: "N4" },
  { jp: "鈍[にぶ]い", en: "dull, slow", level: "N4" },
  { jp: "不便[ふべん]", en: "inconvenient", level: "N4" },
  { jp: "安全[あんぜん]", en: "safe", level: "N4" },
  { jp: "危険[きけん]", en: "dangerous", level: "N4" },
  { jp: "簡単[かんたん]", en: "simple, easy", level: "N4" },
  { jp: "複雑[ふくざつ]", en: "complicated", level: "N4" },
  { jp: "丁寧[ていねい]", en: "polite, careful", level: "N4" },
  { jp: "失礼[しつれい]", en: "rude, excuse me", level: "N4" },
  { jp: "正直[しょうじき]", en: "honest", level: "N4" },
  { jp: "真面目[まじめ]", en: "serious, diligent", level: "N4" },
  { jp: "熱心[ねっしん]", en: "enthusiastic, eager", level: "N4" },
  { jp: "盛[さか]ん", en: "popular, prosperous", level: "N4" },
  { jp: "適当[てきとう]", en: "suitable, appropriate", level: "N4" },
  { jp: "十分[じゅうぶん]", en: "enough, sufficient", level: "N4" },
  { jp: "必要[ひつよう]", en: "necessary", level: "N4" },
  { jp: "可能[かのう]", en: "possible", level: "N4" },
  { jp: "不可能[ふかのう]", en: "impossible", level: "N4" },
  { jp: "確[たし]か", en: "certain, sure", level: "N4" },
  { jp: "無理[むり]", en: "impossible, unreasonable", level: "N4" },
  { jp: "駄目[だめ]", en: "no good, useless", level: "N4" },
  { jp: "残念[ざんねん]", en: "regrettable, disappointing", level: "N4" },
  { jp: "大丈夫[だいじょうぶ]", en: "OK, all right", level: "N4" },
  { jp: "変[へん]", en: "strange", level: "N4" },
  { jp: "特別[とくべつ]", en: "special", level: "N4" },
  { jp: "自由[じゆう]", en: "free, liberty", level: "N4" },
  { jp: "幸[しあわ]せ", en: "happiness", level: "N4" },
  { jp: "豊[ゆた]か", en: "abundant, wealthy", level: "N4" },
  { jp: "素敵[すてき]", en: "lovely, nice", level: "N4" },
  { jp: "勝手[かって]", en: "selfish, one's own way", level: "N4" },
  { jp: "急[きゅう]", en: "sudden, urgent", level: "N4" },
  { jp: "楽[らく]", en: "comfortable, easy", level: "N4" },
  { jp: "様々[さまざま]", en: "various, diverse", level: "N4" },
  { jp: "必[かなら]ず", en: "certainly, without fail", level: "N4" },
  { jp: "絶対[ぜったい]に", en: "absolutely", level: "N4" },
  { jp: "きっと", en: "surely, certainly", level: "N4" },
  { jp: "もし", en: "if", level: "N4" },
  { jp: "もしも", en: "if (emphatic)", level: "N4" },
  { jp: "例[たと]えば", en: "for example", level: "N4" },
  { jp: "特[とく]に", en: "especially", level: "N4" },
  { jp: "実[じつ]は", en: "actually, in fact", level: "N4" },
  { jp: "確[たし]かに", en: "certainly, surely", level: "N4" },
  { jp: "多[おお]く", en: "many, much", level: "N4" },
  { jp: "ずっと", en: "all along, much more", level: "N4" },
  { jp: "とうとう", en: "finally, at last", level: "N4" },
  { jp: "やっと", en: "at last, finally", level: "N4" },
  { jp: "急[きゅう]に", en: "suddenly", level: "N4" },
  { jp: "突然[とつぜん]", en: "suddenly", level: "N4" },
  { jp: "偶[たま]に", en: "occasionally", level: "N4" },
  { jp: "次[つぎ]に", en: "next", level: "N4" },
  { jp: "最初[さいしょ]に", en: "at first", level: "N4" },
  { jp: "最後[さいご]に", en: "at last, finally", level: "N4" },
  { jp: "先[さき]に", en: "ahead, beforehand", level: "N4" },
  { jp: "後[あと]で", en: "later", level: "N4" },
  { jp: "全[まった]く", en: "completely, entirely", level: "N4" },
  { jp: "随分[ずいぶん]", en: "very, considerably", level: "N4" },
  { jp: "なるべく", en: "as much as possible", level: "N4" },
  { jp: "出来[でき]るだけ", en: "as much as possible", level: "N4" },
  { jp: "決[けっ]して", en: "never (with negative)", level: "N4" },
  { jp: "別[べつ]に", en: "(not) particularly", level: "N4" },
  { jp: "特別[とくべつ]に", en: "especially", level: "N4" },
  { jp: "わざわざ", en: "expressly, taking the trouble", level: "N4" },
  { jp: "やはり", en: "as expected, after all", level: "N4" },
  { jp: "やっぱり", en: "as expected (casual)", level: "N4" },
  { jp: "なかなか", en: "very, quite, (not) easily", level: "N4" },
  { jp: "そろそろ", en: "soon, about time", level: "N4" },
  { jp: "ちっとも", en: "(not) at all", level: "N4" },
  { jp: "しっかり", en: "firmly, properly", level: "N4" },
  { jp: "はっきり", en: "clearly", level: "N4" },
  { jp: "ぴったり", en: "exactly, perfectly", level: "N4" },
  { jp: "そっくり", en: "exactly alike", level: "N4" },
  { jp: "それで", en: "and so, therefore", level: "N4" },
  { jp: "それに", en: "moreover, besides", level: "N4" },
  { jp: "それでも", en: "even so", level: "N4" },
  { jp: "けれども", en: "however, but", level: "N4" },
  { jp: "ところが", en: "however, but", level: "N4" },
  { jp: "ところで", en: "by the way", level: "N4" },
  { jp: "つまり", en: "in other words", level: "N4" },
  { jp: "だから", en: "so, therefore", level: "N4" },
  { jp: "ですから", en: "so, therefore (polite)", level: "N4" },
  { jp: "または", en: "or, otherwise", level: "N4" },
  { jp: "もしくは", en: "or", level: "N4" },
  { jp: "そのうえ", en: "in addition", level: "N4" },
  { jp: "更[さら]に", en: "furthermore", level: "N4" },
  { jp: "尚[なお]", en: "furthermore, still", level: "N4" },
  { jp: "なるほど", en: "I see, indeed", level: "N4" },
];
