// Vocabulary data.
// Furigana syntax: kanji[reading] — only the kanji portion gets a reading.
// Examples:
//   "食[た]べる"      → 食(た)べる
//   "学校[がっこう]"   → 学校(がっこう)
//   "あした"          → just あした (no ruby)
//   "お母[かあ]さん"   → お母(かあ)さん
//
// Add more words freely. Keep `level` as "N5" or "N4".

const VOCAB = [
  // ===== N5 =====
  { jp: "私[わたし]", en: "I, me", level: "N5" },
  { jp: "貴方[あなた]", en: "you", level: "N5" },
  { jp: "人[ひと]", en: "person", level: "N5" },
  { jp: "日本[にほん]", en: "Japan", level: "N5" },
  { jp: "日本語[にほんご]", en: "Japanese (language)", level: "N5" },
  { jp: "英語[えいご]", en: "English (language)", level: "N5" },
  { jp: "学校[がっこう]", en: "school", level: "N5" },
  { jp: "先生[せんせい]", en: "teacher", level: "N5" },
  { jp: "学生[がくせい]", en: "student", level: "N5" },
  { jp: "友達[ともだち]", en: "friend", level: "N5" },
  { jp: "家[いえ]", en: "house, home", level: "N5" },
  { jp: "家族[かぞく]", en: "family", level: "N5" },
  { jp: "父[ちち]", en: "father (own)", level: "N5" },
  { jp: "母[はは]", en: "mother (own)", level: "N5" },
  { jp: "お父[とう]さん", en: "father", level: "N5" },
  { jp: "お母[かあ]さん", en: "mother", level: "N5" },
  { jp: "兄[あに]", en: "older brother (own)", level: "N5" },
  { jp: "姉[あね]", en: "older sister (own)", level: "N5" },
  { jp: "弟[おとうと]", en: "younger brother", level: "N5" },
  { jp: "妹[いもうと]", en: "younger sister", level: "N5" },
  { jp: "水[みず]", en: "water", level: "N5" },
  { jp: "お茶[ちゃ]", en: "tea", level: "N5" },
  { jp: "コーヒー", en: "coffee", level: "N5" },
  { jp: "ご飯[はん]", en: "rice, meal", level: "N5" },
  { jp: "肉[にく]", en: "meat", level: "N5" },
  { jp: "魚[さかな]", en: "fish", level: "N5" },
  { jp: "野菜[やさい]", en: "vegetable", level: "N5" },
  { jp: "果物[くだもの]", en: "fruit", level: "N5" },
  { jp: "本[ほん]", en: "book", level: "N5" },
  { jp: "新聞[しんぶん]", en: "newspaper", level: "N5" },
  { jp: "車[くるま]", en: "car", level: "N5" },
  { jp: "電車[でんしゃ]", en: "train", level: "N5" },
  { jp: "駅[えき]", en: "station", level: "N5" },
  { jp: "店[みせ]", en: "shop, store", level: "N5" },
  { jp: "今日[きょう]", en: "today", level: "N5" },
  { jp: "明日[あした]", en: "tomorrow", level: "N5" },
  { jp: "昨日[きのう]", en: "yesterday", level: "N5" },
  { jp: "今[いま]", en: "now", level: "N5" },
  { jp: "時間[じかん]", en: "time, hour", level: "N5" },
  { jp: "朝[あさ]", en: "morning", level: "N5" },
  { jp: "昼[ひる]", en: "noon, daytime", level: "N5" },
  { jp: "夜[よる]", en: "night", level: "N5" },
  { jp: "食[た]べる", en: "to eat", level: "N5" },
  { jp: "飲[の]む", en: "to drink", level: "N5" },
  { jp: "見[み]る", en: "to see, to watch", level: "N5" },
  { jp: "聞[き]く", en: "to listen, to ask", level: "N5" },
  { jp: "話[はな]す", en: "to speak", level: "N5" },
  { jp: "読[よ]む", en: "to read", level: "N5" },
  { jp: "書[か]く", en: "to write", level: "N5" },
  { jp: "行[い]く", en: "to go", level: "N5" },
  { jp: "来[く]る", en: "to come", level: "N5" },
  { jp: "帰[かえ]る", en: "to return home", level: "N5" },
  { jp: "買[か]う", en: "to buy", level: "N5" },
  { jp: "する", en: "to do", level: "N5" },
  { jp: "ある", en: "to exist (inanimate)", level: "N5" },
  { jp: "いる", en: "to exist (animate)", level: "N5" },
  { jp: "大[おお]きい", en: "big", level: "N5" },
  { jp: "小[ちい]さい", en: "small", level: "N5" },
  { jp: "新[あたら]しい", en: "new", level: "N5" },
  { jp: "古[ふる]い", en: "old (not for people)", level: "N5" },
  { jp: "高[たか]い", en: "expensive, tall", level: "N5" },
  { jp: "安[やす]い", en: "cheap", level: "N5" },
  { jp: "良[い]い", en: "good", level: "N5" },
  { jp: "悪[わる]い", en: "bad", level: "N5" },
  { jp: "暑[あつ]い", en: "hot (weather)", level: "N5" },
  { jp: "寒[さむ]い", en: "cold (weather)", level: "N5" },

  // ===== N4 =====
  { jp: "経験[けいけん]", en: "experience", level: "N4" },
  { jp: "意見[いけん]", en: "opinion", level: "N4" },
  { jp: "理由[りゆう]", en: "reason", level: "N4" },
  { jp: "説明[せつめい]", en: "explanation", level: "N4" },
  { jp: "質問[しつもん]", en: "question", level: "N4" },
  { jp: "答[こた]え", en: "answer", level: "N4" },
  { jp: "約束[やくそく]", en: "promise, appointment", level: "N4" },
  { jp: "用事[ようじ]", en: "errand, business to attend to", level: "N4" },
  { jp: "予定[よてい]", en: "plan, schedule", level: "N4" },
  { jp: "場所[ばしょ]", en: "place, location", level: "N4" },
  { jp: "受付[うけつけ]", en: "reception desk", level: "N4" },
  { jp: "案内[あんない]", en: "guidance, information", level: "N4" },
  { jp: "市民[しみん]", en: "citizen", level: "N4" },
  { jp: "社会[しゃかい]", en: "society", level: "N4" },
  { jp: "文化[ぶんか]", en: "culture", level: "N4" },
  { jp: "歴史[れきし]", en: "history", level: "N4" },
  { jp: "政治[せいじ]", en: "politics", level: "N4" },
  { jp: "経済[けいざい]", en: "economy", level: "N4" },
  { jp: "産業[さんぎょう]", en: "industry", level: "N4" },
  { jp: "工場[こうじょう]", en: "factory", level: "N4" },
  { jp: "技術[ぎじゅつ]", en: "technology, skill", level: "N4" },
  { jp: "機械[きかい]", en: "machine", level: "N4" },
  { jp: "道具[どうぐ]", en: "tool", level: "N4" },
  { jp: "材料[ざいりょう]", en: "materials, ingredients", level: "N4" },
  { jp: "原料[げんりょう]", en: "raw materials", level: "N4" },
  { jp: "輸出[ゆしゅつ]", en: "export", level: "N4" },
  { jp: "輸入[ゆにゅう]", en: "import", level: "N4" },
  { jp: "計画[けいかく]", en: "plan, project", level: "N4" },
  { jp: "準備[じゅんび]", en: "preparation", level: "N4" },
  { jp: "用意[ようい]", en: "preparation, arrangements", level: "N4" },
  { jp: "確[たし]かめる", en: "to verify, to make sure", level: "N4" },
  { jp: "比[くら]べる", en: "to compare", level: "N4" },
  { jp: "選[えら]ぶ", en: "to choose", level: "N4" },
  { jp: "決[き]める", en: "to decide", level: "N4" },
  { jp: "続[つづ]ける", en: "to continue", level: "N4" },
  { jp: "始[はじ]める", en: "to begin (something)", level: "N4" },
  { jp: "止[や]める", en: "to quit, to stop doing", level: "N4" },
  { jp: "考[かんが]える", en: "to think, to consider", level: "N4" },
  { jp: "調[しら]べる", en: "to investigate, to check", level: "N4" },
  { jp: "答[こた]える", en: "to answer", level: "N4" },
  { jp: "覚[おぼ]える", en: "to remember, to learn", level: "N4" },
  { jp: "忘[わす]れる", en: "to forget", level: "N4" },
  { jp: "教[おし]える", en: "to teach, to tell", level: "N4" },
  { jp: "習[なら]う", en: "to learn (from a teacher)", level: "N4" },
  { jp: "便利[べんり]", en: "convenient", level: "N4" },
  { jp: "不便[ふべん]", en: "inconvenient", level: "N4" },
  { jp: "安全[あんぜん]", en: "safe, safety", level: "N4" },
  { jp: "危険[きけん]", en: "danger, dangerous", level: "N4" },
  { jp: "簡単[かんたん]", en: "simple, easy", level: "N4" },
  { jp: "複雑[ふくざつ]", en: "complicated", level: "N4" },
  { jp: "丁寧[ていねい]", en: "polite, careful", level: "N4" },
  { jp: "親切[しんせつ]", en: "kind", level: "N4" },
];
